name: Setup Node.js and Install deps
description: Setup Node.js/pnpm. Install dependencies.
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'
    - name: Update npm to latest (for trusted publishing)
      run: npm i -g npm@latest
      shell: bash
    - name: Install deps
      run: pnpm install
      shell: bash
