[package]
edition = "2021"
name = "typed-cstruct_generator"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["napi4"] }
napi-derive = "2.12.2"

syn = { version = "2.0", features = ["parsing", "visit"] }
bindgen = "0.72"

phf = { version = "0.11", features = ["macros"] }

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"

[dev-dependencies]
insta = "1.41.1"
