/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function generate(headers: Array<string>, dumpRustCode?: boolean | undefined | null, clangArgs?: Array<string> | undefined | null): string
