name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: pnpm check
      - run: pnpm build
        working-directory: packages/typed-cstruct
      - run: pnpm test
        working-directory: packages/typed-cstruct

  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/typed-cstruct
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: pnpm coverage
      - uses: codecov/codecov-action@v5
        with:
          files: ./packages/typed-cstruct/coverage/coverage-final.json
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
      - run: cargo test --all
