name: Release
on:
  push:
    tags:
      - '@typed-cstruct/generator@v*'

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/generator
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: actions/download-artifact@v4
        with:
          path: packages/generator/artifacts
      - run: pnpm artifacts
      - run: ls -R ./npm
      - run: pnpm run version
      - run: pnpm -r publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
