name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: packages/typed-cstruct
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-node

      - run: pnpm publish --no-git-checks --tag latest --access public
