name: Release
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: actions/download-artifact@v4
        with:
          path: packages/generator
      - run: ls packages/generator
      - run: pnpm --dir packages/generator move-binaries
      - run: ls -R packages/generator/npm
      - run: pnpm --dir packages/generator run version
      - run: pnpm --dir packages/generator -r publish --dry-run 
