name: Release
on:
  push:
    tags:
      - '@typed-cstruct/generator@v*'

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: packages/generator
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: actions/download-artifact@v4
        with:
          path: packages/generator/artifacts
      - run: pnpm artifacts
      - run: ls -R ./npm
      - run: pnpm run version

      - name: Set Publishing Config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: pnpm -r publish --no-git-checks --tag latest --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
